services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Mindy\Template\Library\LibraryInterface:
            public: true
            tags: ['template.library']

    Company\Bundle\AppBundle\:
        resource: '../../*'
        exclude: '../../{Model,Tests,vendor}'

    Company\Bundle\AppBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
