imports:
    - { resource: parameters.yml }
    - { resource: admin.yml }
    - { resource: imagine.yml }

form:
    themes:
        - 'default'
        - 'flexy'

sitemap:
    host: super-site.com
    scheme: https
    save_path: '%kernel.root_dir%/../web'

ivory_ck_editor:
    configs:
        default:
            filebrowserBrowseUrl: "/core/file/list?wysiwyg=ckeditor"
            filebrowserWindowWidth: 800
            filebrowserWindowHeight: 500
            toolbar: 'default_toolbar'
            language: ru

    toolbars:
        configs:
            default_toolbar: [ '@basic', '@paste', '-', '@media', '-', "@link", "-", "@extra" ]
        items:
            basic: ['Bold', 'Italic', 'Strike', 'RemoveFormat', 'Blockquote', 'Styles', 'Format', 'Table', 'HorizontalRule']
            list: ['NumberedList', 'BulletedList']
            media: ['Image']
            paste: ['PasteText', 'PasteFromWord']
            link: ['Link', 'Unlink', 'Anchor']
            extra: ['Templates', 'Source', '-', 'Maximize']

oneup_flysystem:
    adapters:
        default:
            local:
                directory: '%file.local_directory%'
    filesystems:
        default:
            adapter: default

monolog:
    handlers:
        file_log:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            max_files: 10

framework:
    csrf_protection: true
    form: true
    validation:
        enabled: true
        enable_annotations: false
    templating:
        engines: ['mindy']
    assets:
        version: 'v1'
        version_format: '%%s?v=%%s'
        base_path: ~
        packages:
            media:
                base_path: /media/
    serializer:
        enabled: true
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
    session:
        handler_id: ~
    translator:
        enabled: true
        fallbacks: [en]
    router:
        enabled: true
        resource: "%kernel.root_dir%/config/routing.yml"

sensio_framework_extra:
    router: { annotations: false }
    request: { converters: true, auto_convert: true }
    view: { annotations: false }
    cache: { annotations: false }
    security: { annotations: false }
    # Defaults to true if the PSR-7 bridge is installed
    psr_message: { enabled: false }

swiftmailer:
    transport: smtp
    username: noreply@site.com
    password: super_secret
    host: smtp.yandex.ru
    port: 465
    encryption: ssl
    spool:
        type: file
        path: '%kernel.root_dir%/spool'
    sender_address: noreply@site.com