imports:
    - { resource: config_dev.yml }

orm:
    connections:
        default:
            memory: true
            driver: pdo_sqlite

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

swiftmailer:
    transport: ~