imports:
    - { resource: config.yml }

template:
    mode: -1

orm:
    connections:
        default:
            dbname: my_db
            host: localhost
            port: 3306
            user: root
            password: ''
            driver: pdo_mysql

sentry:
    dsn: "https://public:secret@sentry.example.com/1"

services:
    mindy.bundle.mindy.example:
        class: Mindy\Bundle\MindyBundle\EventListener\ExceptionListener
        arguments: [ "@template", "@logger", "mindy/error/%s.html" ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }