imports:
    - { resource: config.yml }

orm:
    connections:
        default:
            dbname: my_db
            host: localhost
            port: 3306
            user: root
            password: ''
            driver: pdo_mysql

monolog:
    handlers:
        console:
            type: console
        file_log:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 10
        syslog_handler:
            type: syslog
            level: error

