parameters:
    mail.from: "noreply@my-site.com"
    kernel.charset: UTF-8
    kernel.secret: very-secret
    kernel.default_locale: ru

monolog:
    handlers:
        file_log:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            max_files: 10

framework:
    csrf_protection: true
    form: true
    validation:
        enabled: true
        enable_annotations: false
    templating:
        engines: ['php']
    assets:
        version: 'v1'
        version_format: '%%s?v=%%s'
        base_path: ~
        packages:
            media:
                base_path: /media/
    serializer:
        enabled: true
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
    session:
        handler_id: ~
    translator:
        enabled: true
        fallbacks: [en]
    router:
        enabled: true
        resource: "%kernel.root_dir%/config/routing.yml"

sensio_framework_extra:
    router: { annotations: false }
    request: { converters: true, auto_convert: true }
    view: { annotations: false }
    cache: { annotations: false }
    security: { annotations: false }
    # Defaults to true if the PSR-7 bridge is installed
    psr_message: { enabled: false }