admin:
    menu:
        -
            name: 'SEO'
            route: 'admin_seo_seo_list'
            children:
                -
                    name: 'Мета шаблоны'
                    route: 'admin_seo_template_list'
