framework:
    csrf_protection: true
    form: true
    validation:
        enable_annotations: false
    templating:
        engines: ['mindy']
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    serializer:
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
    session:
        handler_id: ~
    translator:
        fallbacks: [en]
    router:
        resource: "%kernel.project_dir%/config/routing.yaml"
