framework:
    csrf_protection: true
    form: true
    validation:
        enabled: true
        enable_annotations: false
    templating:
        engines: ['mindy']
    assets:
        version: 'v1'
        version_format: '%%s?v=%%s'
        base_path: ~
        packages:
            media:
                base_path: /media/
    serializer:
        enabled: true
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
    session:
        handler_id: ~
    translator:
        enabled: true
        fallbacks: [en]
    router:
        enabled: true
        resource: "%kernel.root_dir%/config/routing.yml"
