security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        admin:
            memory:
                users:
                    admin: { password: admin, roles: 'ROLE_ADMIN' }

    firewalls:
        admin:
            pattern: ^/admin
            provider: admin
            context: admin
            anonymous: ~
            switch_user: { role: ROLE_ADMIN }
            form_login:
                login_path: admin_login
                check_path: admin_login
            logout:
                path: admin_logout
                target: /
                invalidate_session: true
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /admin/
                domain: ~

    access_control:
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }

        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

